server:
  port: 8081

spring:
  application:
    name: notification
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  kafka:
    bootstrap-servers: localhost:9092